//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use super::sea_orm_active_enums::AttemptStatusEnum;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "assessment_attempts")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub student_id: Uuid,
    pub concept_id: Uuid,
    pub started_at: DateTimeWithTimeZone,
    pub completed_at: Option<DateTimeWithTimeZone>,
    pub status: AttemptStatusEnum,
    pub current_solo_level_id: Uuid,
    pub target_solo_level_id: Uuid,
    pub is_mastered: bool,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::concepts::Entity",
        from = "Column::ConceptId",
        to = "super::concepts::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Concepts,
    #[sea_orm(
        belongs_to = "super::solo_levels::Entity",
        from = "Column::CurrentSoloLevelId",
        to = "super::solo_levels::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    SoloLevels2,
    #[sea_orm(
        belongs_to = "super::solo_levels::Entity",
        from = "Column::TargetSoloLevelId",
        to = "super::solo_levels::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    SoloLevels1,
    #[sea_orm(has_many = "super::student_answers::Entity")]
    StudentAnswers,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::StudentId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Users,
}

impl Related<super::concepts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Concepts.def()
    }
}

impl Related<super::student_answers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StudentAnswers.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
