//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "concepts")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub code: String,
    pub name: String,
    pub is_active: bool,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::isomorphic_sets::Entity")]
    IsomorphicSets,
    #[sea_orm(has_many = "super::learning_objective_concepts::Entity")]
    LearningObjectiveConcepts,
    #[sea_orm(has_many = "super::questions::Entity")]
    Questions,
}

impl Related<super::isomorphic_sets::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IsomorphicSets.def()
    }
}

impl Related<super::learning_objective_concepts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LearningObjectiveConcepts.def()
    }
}

impl Related<super::questions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Questions.def()
    }
}

impl Related<super::learning_objectives::Entity> for Entity {
    fn to() -> RelationDef {
        super::learning_objective_concepts::Relation::LearningObjectives.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::learning_objective_concepts::Relation::Concepts
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
