//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "concept_prerequisites")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub concept_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub prerequisite_concept_id: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::concepts::Entity",
        from = "Column::ConceptId",
        to = "super::concepts::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Concepts2,
    #[sea_orm(
        belongs_to = "super::concepts::Entity",
        from = "Column::PrerequisiteConceptId",
        to = "super::concepts::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Concepts1,
}

impl ActiveModelBehavior for ActiveModel {}
