//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "isomorphic_sets")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub concept_id: Uuid,
    pub title: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub is_active: bool,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::concepts::Entity",
        from = "Column::ConceptId",
        to = "super::concepts::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Concepts,
    #[sea_orm(has_many = "super::isomorphic_set_questions::Entity")]
    IsomorphicSetQuestions,
}

impl Related<super::concepts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Concepts.def()
    }
}

impl Related<super::isomorphic_set_questions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IsomorphicSetQuestions.def()
    }
}

impl Related<super::questions::Entity> for Entity {
    fn to() -> RelationDef {
        super::isomorphic_set_questions::Relation::Questions.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::isomorphic_set_questions::Relation::IsomorphicSets
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
