//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "isomorphic_set_questions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub isomorphic_set_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false, unique)]
    pub question_id: Uuid,
    pub display_order: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::isomorphic_sets::Entity",
        from = "Column::IsomorphicSetId",
        to = "super::isomorphic_sets::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    IsomorphicSets,
    #[sea_orm(
        belongs_to = "super::questions::Entity",
        from = "Column::QuestionId",
        to = "super::questions::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Questions,
}

impl Related<super::isomorphic_sets::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IsomorphicSets.def()
    }
}

impl Related<super::questions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Questions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
