//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "learning_objective_concepts")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub learning_objective_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub concept_id: Uuid,
    pub display_order: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::concepts::Entity",
        from = "Column::ConceptId",
        to = "super::concepts::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Concepts,
    #[sea_orm(
        belongs_to = "super::learning_objectives::Entity",
        from = "Column::LearningObjectiveId",
        to = "super::learning_objectives::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    LearningObjectives,
}

impl Related<super::concepts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Concepts.def()
    }
}

impl Related<super::learning_objectives::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LearningObjectives.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
