//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "learning_objectives")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub course_id: Uuid,
    pub code: String,
    pub title: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub display_order: i32,
    pub is_active: bool,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::courses::Entity",
        from = "Column::CourseId",
        to = "super::courses::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Courses,
    #[sea_orm(has_many = "super::learning_objective_concepts::Entity")]
    LearningObjectiveConcepts,
}

impl Related<super::courses::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Courses.def()
    }
}

impl Related<super::learning_objective_concepts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LearningObjectiveConcepts.def()
    }
}

impl Related<super::concepts::Entity> for Entity {
    fn to() -> RelationDef {
        super::learning_objective_concepts::Relation::Concepts.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::learning_objective_concepts::Relation::LearningObjectives
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
