//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

pub mod prelude;

pub mod academic_terms;
pub mod assessment_attempts;
pub mod concepts;
pub mod course_offerings;
pub mod courses;
pub mod isomorphic_set_questions;
pub mod isomorphic_sets;
pub mod learning_objective_concepts;
pub mod learning_objectives;
pub mod password_reset_tokens;
pub mod question_concepts;
pub mod question_options;
pub mod question_types;
pub mod questions;
pub mod sea_orm_active_enums;
pub mod solo_levels;
pub mod student_answers;
pub mod users;
