//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

pub use super::academic_terms::Entity as AcademicTerms;
pub use super::assessment_attempts::Entity as AssessmentAttempts;
pub use super::concepts::Entity as Concepts;
pub use super::course_offerings::Entity as CourseOfferings;
pub use super::courses::Entity as Courses;
pub use super::isomorphic_set_questions::Entity as IsomorphicSetQuestions;
pub use super::isomorphic_sets::Entity as IsomorphicSets;
pub use super::learning_objective_concepts::Entity as LearningObjectiveConcepts;
pub use super::learning_objectives::Entity as LearningObjectives;
pub use super::question_concepts::Entity as QuestionConcepts;
pub use super::question_options::Entity as QuestionOptions;
pub use super::question_types::Entity as QuestionTypes;
pub use super::questions::Entity as Questions;
pub use super::solo_levels::Entity as SoloLevels;
pub use super::student_answers::Entity as StudentAnswers;
pub use super::users::Entity as Users;
