//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use super::sea_orm_active_enums::QuestionPurposeEnum;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "question_concepts")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub question_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub concept_id: Uuid,
    pub solo_level_id: Uuid,
    pub purpose: QuestionPurposeEnum,
    pub is_primary: bool,
    pub display_order: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::concepts::Entity",
        from = "Column::ConceptId",
        to = "super::concepts::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Concepts,
    #[sea_orm(
        belongs_to = "super::questions::Entity",
        from = "Column::QuestionId",
        to = "super::questions::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Questions,
    #[sea_orm(
        belongs_to = "super::solo_levels::Entity",
        from = "Column::SoloLevelId",
        to = "super::solo_levels::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    SoloLevels,
}

impl Related<super::concepts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Concepts.def()
    }
}

impl Related<super::questions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Questions.def()
    }
}

impl Related<super::solo_levels::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SoloLevels.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
