//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "questions")]
pub struct Model
{
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub question_type_id: Uuid,
    pub created_by: Uuid,
    pub title: String,
    #[sea_orm(column_type = "Text")]
    pub question_text: String,
    pub estimated_minutes: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub reference_explanation: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub feedback: Option<String>,
    pub is_active: bool,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub course_id: Uuid,
    pub code: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation
{
    #[sea_orm(
        belongs_to = "super::courses::Entity",
        from = "Column::CourseId",
        to = "super::courses::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Courses,
    #[sea_orm(has_one = "super::isomorphic_set_questions::Entity")]
    IsomorphicSetQuestions,
    #[sea_orm(has_many = "super::question_concepts::Entity")]
    QuestionConcepts,
    #[sea_orm(has_many = "super::question_options::Entity")]
    QuestionOptions,
    #[sea_orm(
        belongs_to = "super::question_types::Entity",
        from = "Column::QuestionTypeId",
        to = "super::question_types::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    QuestionTypes,
    #[sea_orm(has_many = "super::student_answers::Entity")]
    StudentAnswers,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::CreatedBy",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    Users,
}

impl Related<super::courses::Entity> for Entity
{
    fn to() -> RelationDef
    {
        Relation::Courses.def()
    }
}

impl Related<super::isomorphic_set_questions::Entity> for Entity
{
    fn to() -> RelationDef
    {
        Relation::IsomorphicSetQuestions.def()
    }
}

impl Related<super::question_concepts::Entity> for Entity
{
    fn to() -> RelationDef
    {
        Relation::QuestionConcepts.def()
    }
}

impl Related<super::question_options::Entity> for Entity
{
    fn to() -> RelationDef
    {
        Relation::QuestionOptions.def()
    }
}

impl Related<super::question_types::Entity> for Entity
{
    fn to() -> RelationDef
    {
        Relation::QuestionTypes.def()
    }
}

impl Related<super::student_answers::Entity> for Entity
{
    fn to() -> RelationDef
    {
        Relation::StudentAnswers.def()
    }
}

impl Related<super::users::Entity> for Entity
{
    fn to() -> RelationDef
    {
        Relation::Users.def()
    }
}

impl Related<super::isomorphic_sets::Entity> for Entity
{
    fn to() -> RelationDef
    {
        super::isomorphic_set_questions::Relation::IsomorphicSets.def()
    }

    fn via() -> Option<RelationDef>
    {
        Some(
            super::isomorphic_set_questions::Relation::Questions
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
