//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "semester_enum")]
pub enum SemesterEnum {
    #[sea_orm(string_value = "odd")]
    Odd,
    #[sea_orm(string_value = "even")]
    Even,
    #[sea_orm(string_value = "ganjil")]
    Ganjil,
    #[sea_orm(string_value = "genap")]
    Genap,
    #[sea_orm(string_value = "antara")]
    Antara,
    #[sea_orm(string_value = "spring")]
    Spring,
    #[sea_orm(string_value = "fall")]
    Fall,
    #[sea_orm(string_value = "summer")]
    Summer,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "solo_level_enum")]
pub enum SoloLevelEnum {
    #[sea_orm(string_value = "prestructural")]
    Prestructural,
    #[sea_orm(string_value = "unistructural")]
    Unistructural,
    #[sea_orm(string_value = "multistructural")]
    Multistructural,
    #[sea_orm(string_value = "relational")]
    Relational,
    #[sea_orm(string_value = "extended_abstract")]
    ExtendedAbstract,
}
