//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, ToSchema)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "attempt_status_enum"
)]
pub enum AttemptStatusEnum {
    #[sea_orm(string_value = "in_progress")]
    InProgress,
    #[sea_orm(string_value = "completed")]
    Completed,
    #[sea_orm(string_value = "abandoned")]
    Abandoned,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Deserialize, Serialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "question_purpose_enum"
)]
pub enum QuestionPurposeEnum {
    #[sea_orm(string_value = "assessment")]
    Assessment,
    #[sea_orm(string_value = "practice")]
    Practice,
    #[sea_orm(string_value = "remediation")]
    Remediation,
    #[sea_orm(string_value = "reflection")]
    Reflection,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "semester_enum")]
pub enum SemesterEnum {
    #[sea_orm(string_value = "odd")]
    Odd,
    #[sea_orm(string_value = "even")]
    Even,
    #[sea_orm(string_value = "ganjil")]
    Ganjil,
    #[sea_orm(string_value = "genap")]
    Genap,
    #[sea_orm(string_value = "antara")]
    Antara,
    #[sea_orm(string_value = "spring")]
    Spring,
    #[sea_orm(string_value = "fall")]
    Fall,
    #[sea_orm(string_value = "summer")]
    Summer,
}
