//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "solo_levels")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub code: String,
    pub name: String,
    #[sea_orm(unique)]
    pub order_index: i16,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub is_active: bool,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::question_concepts::Entity")]
    QuestionConcepts,
}

impl Related<super::question_concepts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::QuestionConcepts.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
