//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "student_answers")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub assessment_attempt_id: Uuid,
    pub question_id: Uuid,
    #[sea_orm(column_type = "Text", nullable)]
    pub answer_text: Option<String>,
    pub selected_option_id: Option<Uuid>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub answer_json: Option<Json>,
    pub is_correct: bool,
    #[sea_orm(column_type = "Float")]
    pub score: f32,
    #[sea_orm(column_type = "Text", nullable)]
    pub feedback: Option<String>,
    pub answered_at: DateTimeWithTimeZone,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::assessment_attempts::Entity",
        from = "Column::AssessmentAttemptId",
        to = "super::assessment_attempts::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    AssessmentAttempts,
    #[sea_orm(
        belongs_to = "super::question_options::Entity",
        from = "Column::SelectedOptionId",
        to = "super::question_options::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    QuestionOptions,
    #[sea_orm(
        belongs_to = "super::questions::Entity",
        from = "Column::QuestionId",
        to = "super::questions::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Questions,
}

impl Related<super::assessment_attempts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AssessmentAttempts.def()
    }
}

impl Related<super::question_options::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::QuestionOptions.def()
    }
}

impl Related<super::questions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Questions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
